import { Manrope } from "next/font/google";
import "./globals.css";
import Providers from "@/components/context/providers";
import Navbar from "@/components/ui/layout/Navbar";
import Footer from "@/components/ui/layout/Footer";

export const metadata = {
  title: "Audiophile E-commerce Store",
  description: "Generated by create next app",
};

const man = Manrope({
  variable: "--font-man",
  display: "swap",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${man.variable}`}>
      <body>
        <div id="drawer-root"></div>
        <div id="mob-nav"></div>

        <Providers>
          <Navbar />
          <div className="min-h-screen">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
