import getAllProducts from "@/components/data/getAllProducts";
import { Product } from "@/prisma/types";

export const metadata = {
  title: "Headphones",
  description: "Generated by create next app",
};

export default async function page() {
  // const productsData: Promise<Product> = getAllProducts();
  // const products = await Promise.all([productsData]);
  return (
    <div>
      <h1>cool</h1>
    </div>
  );
}
